modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "noindium"
version = "${version}"
displayName = "Opt 'NOT' Fine ! (No Indium? Forge Port)"
logoFile= "icon.png"
credits="Luligabi1,TexTrue"
authors = "TexTrueStudio"
description = "A small, jij-able mod for maximum warning to players who have OptiFine installed."

[[dependencies.noindium]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"